version: '3.8'

services:
  api-image:
    # O Swarm agora baixa a imagem pronta do registro do GitHub
    image: ghcr.io/daniel-vitorelli/futebol-image:latest
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - PORT=3000
      - NODE_ENV=production
      - API_SECRET_KEY=${API_SECRET_KEY}
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      - equinox-net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.api-image-service.loadbalancer.server.port=3000"
        - "traefik.http.routers.api-image-main.rule=Host(`api-image.ai-equinox.com`)"
        - "traefik.http.routers.api-image-main.entrypoints=websecure"
        - "traefik.http.routers.api-image-main.tls=true"
        - "traefik.http.routers.api-image-main.tls.certresolver=letsencryptresolver"
        - "traefik.http.routers.api-image-main.service=api-image-service"
        - "traefik.http.routers.api-image-ip.rule=HostRegexp(`{host:5\\.189\\.166\\.47}`)"
        - "traefik.http.routers.api-image-ip.entrypoints=web"
        - "traefik.http.routers.api-image-ip.service=api-image-service"

networks:
  equinox-net:
    external: true
